#!/bin/bash

# Etapa 02 - Configura mirrors, arquitetura 32 bits e base do sistema

step_02_apt_base() {
    show_message "Atualizando mirrors"
    MIRRORS_FILE=/etc/apt/sources.list.d/official-package-repositories.list
    cp "$MIRRORS_FILE" "$USER_HOME/official-package-repositories.list.bkp"
    cat > "$MIRRORS_FILE" <<EOF
# Do not edit this file manually, use Software Sources instead.

deb http://packages.linuxmint.com $LINUXMINT_CODENAME main upstream import backport #id:linuxmint_main

deb http://archive.ubuntu.com/ubuntu $UBUNTU_CODENAME main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu $UBUNTU_CODENAME-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu $UBUNTU_CODENAME-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu/ $UBUNTU_CODENAME-security main restricted universe multiverse
EOF

    show_message "Habilitando pacotes de 32 bits"
    dpkg --add-architecture i386

    show_message "Atualizando repositórios"
    apt-get update

    show_message "Atualizando pacotes"
    apt-get upgrade -y
}
